repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    installed: true
    version: 1.12.0
  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    installed: true
    version: 1.12.0
    wait: true
  - name: istio-ingress
    namespace: istio-ingres
    createNamespace: true
    labels:
      istio-injection: enabled
    chart: istio/gateway
    installed: true
    version: 1.12.0
    wait: true
