repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
- name: istio-base
  namespace: istio-system
  chart: istio/base
  installed: true
- name: istiod
  namespace: istio-system
  chart: istio/istiod
  installed: true
