---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog
  namespace: demo1
spec:
  template:
    spec:
      containers:
        - image: gcr.io/winzana-workshop/knative-kong/blog:v1.0.6
          command: ['node', './dist/apps/api/blog/main.js']
          env:
            - name: port
              value: '8080'
            - name: NODE_ENV
              value: 'production'
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: meteo
  namespace: demo1
spec:
  template:
    spec:
      containers:
        - image: gcr.io/winzana-workshop/knative-kong/meteo:v1.0.6
          command: ['node', './dist/apps/api/meteo/main.js']
          env:
            - name: port
              value: '8080'
            - name: NODE_ENV
              value: 'production'
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: www
  namespace: demo1
spec:
  template:
    spec:
      containers:
        - image: gcr.io/winzana-workshop/knative-kong/front:v1.0.5
